---
# tasks file for ansible_wireguard

- name: Install Wireguard and dependencies
  apt:
    name: 
      - wireguard
      - iptables
    state: present
    update_cache: true

- name: Wireguard server configuration
  include: 'server_configuration.yml'

- name: Wireguard client keys and server configuration
  include: 'client_configuration.yml'
  when: (peers_list is defined) or (peers_list|length != 0)
