---
# tasks file for ansible_wireguard

- name: Add Debian 10 backports repository 
  apt_repository:
    repo: deb http://ftp.debian.org/debian buster-backports main
    update_cache: yes
    state: present
    filename: buster-backports
  when: ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "10"

- name: Install Wireguard and dependencies
  apt:
    name: 
      - wireguard
      - iptables
      - procps
    state: present
    update_cache: true

- name: Wireguard server configuration
  include: 'server_configuration.yml'

- name: Wireguard client keys and server configuration
  include: 'client_configuration.yml'
  when: (peers_list is defined) or (peers_list|length != 0)
