---
# handlers file for ansible_wireguard

- name: Reload Wireguard configuration
  shell: wg syncconf {{ wireguard_interface }} <(wg-quick strip {{ wireguard_interface }})
  args:
    executable: /bin/bash
  changed_when: False
